- name: conditions dempo
  hosts: localhost
  connection: local
  tasks:
  - name: print hello universe
    ansible.builtin.debug:
       msg: hellunviverse print
    when: what == "universe" 
      
  - name: print hello world
    ansible.builtin.debug:
      msg: hello world
    when: what == "world"  