- name: conditions dempo
  hosts: localhost
  connection: local
  tasks:
  - name: print hello universe
    ansible.builtin.debug:
       msg: hellunviverse print
  - name: print hello work
    ansible.builtin.debug:
      msg: hello worls 